### ISSUE TITLE
should be using namespace::autoclean

### ISSUE THREAD

**Issue by karenetheridge** [ioanrogers/Net-LCDproc#3]
namespace::sweep is now obsolete and namespace::autoclean handles more cases, more properly. Anything using Moose, Moo or Mouse should absolutely be using namespace::autoclean; for a few situations (e.g. exporter classes) namespace::clean might be preferable, but a ticket reporting the issue would still be very much welcomed.

(0.16 is the version that dropped the loading of Class::MOP to introspect Moo classes.)

see https://rt.cpan.org/Ticket/Display.html?id=101222

**Comment by ioanrogers** [comment]
Thanks for letting me know @karenetheridge. I went with `namespace::clean` as per https://metacpan.org/pod/release/HAARG/Moo-2.000001/lib/Moo.pm#CLEANING-UP-IMPORTS. It seems to do the job for my simple use case.
